name: Action Practice


on:
  push:
  schedule:
   - cron: "0 14 * * *"
  

env:
  TZ: Asia/Shanghai

jobs:
  # a single job
  a-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: set chromedriver
        uses: nanasess/setup-chromedriver@v2
        with: 
          chromedriver-version: '117.0.5938.92'
      - name: start browser

        run: |
          export DISPLAY=:99 
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
        
      - name: Install requirements   
        run: |
          python3 -m pip install --upgrade pip
          pip3 install selenium==4.9.0 requests beautifulsoup4 lxml asyncio aiohttp nest_asyncio cryptography pycryptodome argparse opencv-python
      - name: Run
        run: python3 ./run.py
      - name: Commit
        env:
          GIT_NAME: GitHub Actions[Bot]
          GIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        
        run: |
          git config --local user.name $GIT_NAME
          git config --local user.email $GIT_EMAIL
          git pull
           
          
          git reset --mixed origin/main
          git add .
          git commit -m "Github action update at `date '+%Y-%m-%d %H:%M:%S'`."
          git push
